config/routes.rb
Rails.application.routes.draw do
  
  mount Ckeditor::Engine => '/ckeditor'

  resources :categories, only: [:show]
  resources :pages, only: [:show]
  namespace :admin do
    resources :types, except: [:show]
    resources :menus, except: [:show]
    resources :pages #/admin/pages
    resources :categories
    resources :settings, only: [ :index, :update, :homepage ]
  end

  Page.where.not(slug: [nil, ""]).all.each do |page|
    get "/#{page.slug}", controller: "pages", action: "show", id: page.id
  end

  
  root to: redirect(Setting.where(key: "homepage").first.value)

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :pages
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, :to => :data

  validates_presence_of :data
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, :mount_on => :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end
end

app/models/field.rb
class Field < ActiveRecord::Base
  belongs_to :page
  belongs_to :field_definition
end

app/models/field_definition.rb
class FieldDefinition < ActiveRecord::Base
  belongs_to :type
end

app/models/menu.rb
class Menu < ActiveRecord::Base
  validates_presence_of :name
  has_many :menu_items

  accepts_nested_attributes_for :menu_items, reject_if: :all_blank
end

app/models/menu_item.rb
class MenuItem < ActiveRecord::Base
  belongs_to :menu
end

app/models/page.rb
class Page < ActiveRecord::Base
  belongs_to :category
  belongs_to :type
end

app/models/setting.rb
class Setting < ActiveRecord::Base
end

app/models/type.rb
class Type < ActiveRecord::Base
  has_many :field_definitions

  accepts_nested_attributes_for :field_definitions, reject_if: :all_blank
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
 def show 
  @category = Category.includes(:pages).find params[:id]
 end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
    @page = Page.find params[:id]
  end

  def homepage 
    @page = Page.first
  end 
end

app/helpers/admin/settings_helper.rb
module Admin::SettingsHelper
  def homepage_options
    grouped_options_for_select({
      "Pages" => Page.all.map { |page| [ page.title, url_for_page(page) ]},
      "Categories" => Category.all.map { |category| [ category.name, category_path(category) ]}
      }, Setting.where(key: "homepage").first.value)
  end 

  def theme_options
    options_for_select(
      @themes.map { |theme| [ "#{theme.name} (by #{theme.author})", theme.id ] },
      Setting.where(key: "theme").first.value
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def url_for_page page

    root_path + 
    if page.slug.present?
      page.slug
    else 
      "pages/#{page.id}"
    end
  end

  def url_for_menu_item menu_item 
    if menu_item.url.match /:\/\// # http://, ftp:// etc
      menu_item.url
    else
      root_path + menu_item.url
    end
  end  

  def target_for_menu_item menu_item 
    if menu_item.url.match /:\/\// # http://, ftp:// etc
      "_blank"
    else
      "_self"
    end
  end    
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/admin/pages/_form.html.haml
= form_for [ "admin", @page ] do |f|
  - if @page.errors.any?
    #error_explanation
      %h2= "#{pluralize(@page.errors.count, "error")} prohibited this page from being saved:"
      %ul
        - @page.errors.full_messages.each do |msg|
          %li= msg


  %p
    = f.label :title
    = f.text_field :title, class: "form-control"
  %p
    = f.label :body
    = f.cktext_area :body, class: "form-control", :ckeditor => {:uiColor => '#ffffff', :toolbar => 'mini'}
  %p
    = f.label :slug
    = f.text_field :slug, class: "form-control"
  %p
    =f.label :category_id
    =f.select :category_id, Category.all.map { |category| [category.name, category.id]}, class: "form-control"
  %p
    =f.hidden_field :type_id
    =f.submit 'Save', class: "btn btn-success"

app/views/admin/pages/edit.html.haml
%h1 Editing page

= render 'form'

= link_to 'Show', admin_page_path(@page)
\|
= link_to 'Back', admin_pages_path

app/views/admin/pages/index.html.haml
%h1 All Pages

%table.table
  %thead
    %tr
      %th Title
      %th Body
      %th Slug
      %th
      %th

  %tbody
    - @pages.each do |page|
      %tr
        %td= link_to page.title, url_for_page(page)
        %td= truncate(strip_tags(page.body), length: 120)
        %td
          %code=url_for_page page
        %td=  link_to 'Edit', edit_admin_page_path(page), class: "label label-info"
        %td= link_to 'Destroy', admin_page_path(page), :method => :delete, :data => { :confirm => 'Are you sure?' }, class: "label label-danger"



%p 
  = link_to 'New Page', new_admin_page_path, class: "btn btn-success"

  - Type.all.each do |type|
    = link_to "New #{type.name}", new_admin_page_path(type: type.name), class: "btn btn-default"

app/views/admin/pages/new.html.haml
%h1 New page

= render 'form'

= link_to 'Back', admin_pages_path

app/views/admin/pages/show.html.haml
%h1= @page.title

=simple_format @page.body

= link_to 'Edit', edit_admin_page_path(@page)
\|
= link_to 'Back', admin_pages_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta(charset='utf-8')
    %title KMS
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    =render "admin_nav"
    .container
      =content_tag :div, notice, class: "flash bg-success" if notice
      =content_tag :div, alert, class: "flash bg-danger" if alert
      = yield

app/views/pages/homepage.html.haml
%h1= @page.title
%em
  = time_ago_in_words @page.created_at
  ago

=  simple_format @page.body

app/views/pages/show.html.haml
%h1= @page.title
%em
  = time_ago_in_words @page.created_at
  ago

=  simple_format @page.body