config/routes.rb
Rails.application.routes.draw do
  
  mount Ckeditor::Engine => '/ckeditor'

  resources :categories, only: [:show]
  resources :pages, only: [:show]
  namespace :admin do
    resources :types, except: [:show]
    resources :menus, except: [:show]
    resources :pages #/admin/pages
    resources :categories
    resources :settings, only: [ :index, :update, :homepage ]
  end

  Page.where.not(slug: [nil, ""]).all.each do |page|
    get "/#{page.slug}", controller: "pages", action: "show", id: page.id
  end

  
  root to: redirect(Setting.where(key: "homepage").first.value)

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :pages
end

app/controllers/admin/categories_controller.rb
module Admin
  class CategoriesController < ApplicationController
    before_action :set_category, only: [:show, :edit, :update, :destroy]

    # GET /categories
    # GET /categories.json
    def index
      @categories = Category.all
    end

    # GET /categories/1
    # GET /categories/1.json
    def show
    end

    # GET /categories/new
    def new
      @category = Category.new
    end

    # GET /categories/1/edit
    def edit
    end

    # POST /categories
    # POST /categories.json
    def create
      @category = Category.new(category_params)

      respond_to do |format|
        if @category.save
          format.html { redirect_to admin_categories_path, notice: 'Category was successfully created.' }
          format.json { render :show, status: :created, location: @category }
        else
          format.html { render :new }
          format.json { render json: @category.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /categories/1
    # PATCH/PUT /categories/1.json
    def update
      respond_to do |format|
        if @category.update(category_params)
          format.html { redirect_to admin_categories_path, notice: 'Category was successfully updated.' }
          format.json { render :show, status: :ok, location: @category }
        else
          format.html { render :edit }
          format.json { render json: @category.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /categories/1
    # DELETE /categories/1.json
    def destroy
      @category.destroy
      respond_to do |format|
        format.html { redirect_to admin_categories_url, notice: 'Category was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_category
        @category = Category.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def category_params
        params.require(:category).permit(:name)
      end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
 def show 
  @category = Category.includes(:pages).find params[:id]
 end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/_form.html.haml
= form_for ["admin", @category] do |f|
  - if @category.errors.any?
    #error_explanation
      %h2= "#{pluralize(@category.errors.count, "error")} prohibited this category from being saved:"
      %ul
        - @category.errors.full_messages.each do |msg|
          %li= msg

  %p
    = f.label :name
    = f.text_field :name, class: "form-control"
  .actions
    = f.submit 'Save', class: "btn btn-success"

app/views/admin/categories/edit.html.haml
%h1 Editing category

= render 'form'

= link_to 'Show', admin_categories_path(@category)
\|
= link_to 'Back', admin_categories_path

app/views/admin/categories/index.html.haml
%h1 Listing categories

%table.table
  %thead
    %tr
      %th Name
      %th
      %th
      %th

  %tbody
    - @categories.each do |category|
      %tr
        %td= category.name
        %td= link_to 'Show', admin_category_path(category)
        %td= link_to 'Edit', edit_admin_category_path(category), class: "label label-info"
        %td= link_to 'Destroy', admin_category_path(category), :method => :delete, :data => { :confirm => 'Are you sure?' }, class: "label label-danger"

%br

%p= link_to 'New Category', new_admin_category_path, class: "btn btn-success"

app/views/admin/categories/new.html.haml
%h1 New category

= render 'form'

= link_to 'Back', admin_categories_path

app/views/admin/categories/show.html.haml
%p
  %b Name:
  = @category.name

= link_to 'Edit', edit_admin_category_path(@category)
\|
= link_to 'Back', admin_categories_path